#!/usr/bin/env bash

echo ". ~/bin/dotfiles/bash/_bashrc" >> ~/.bashrc

# setup configuration files
ln -sf ~/bin/dotfiles/bash/_dircolors ~/.dircolors
ln -sf ~/bin/dotfiles/bash/_inputrc ~/.inputrc
cp ~/bin/dotfiles/git/_gitconfig ~/.gitconfig
ln -sf ~/bin/dotfiles/ruby/_rspec ~/.rspec
ln -sf ~/bin/dotfiles/tmux/_tmux.conf ~/.tmux.conf
ln -sf ~/bin/dotfiles/lynx/_lynxrc ~/.lynxrc
ln -sf ~/bin/dotfiles/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py

# set correct permissions on ssh files
chmod 700 ~/.ssh
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub
chmod 644 ~/.ssh/authorized_keys
chmod 644 ~/.ssh/known_hosts
chmod 644 ~/.ssh/config
