#!/usr/bin/env sh

. ~/bin/dotfiles/python/pyenv.sh
. ~/bin/dotfiles/python/pipx.sh
. ~/bin/dotfiles/node/nvm.sh

# directory shortcuts
export USER_DIR="/mnt/c/Users/$USER" 
export WORK_DIR="/mnt/m/work"
export CURRENT_PROJECT="$PLAY_DIR/python"
