#!/bin/sh

# directory shortcuts
export USER_DIR="/mnt/c/Users/$USER" 
alias bill='cd $USER_DIR'

export WORK_DIR="$USER_DIR/work"
export TUTORIAL_DIR="$WORK_DIR/tutorial"
export PLAY_DIR="$WORK_DIR/play"
export CURRENT_PROJECT="$TUTORIAL_DIR/python"

alias work='cd $WORK_DIR'
alias tut='cd $TUTORIAL_DIR'
alias play='cd $PLAY_DIR'
alias cpro='cd $CURRENT_PROJECT'

. ~/bin/dotfiles/python/_pyenv
. ~/bin/dotfiles/python/_pipx
