#!/bin/sh

#PS1="$FCYN\w $FGRN\$$RS\n"

# directory shortcuts
alias fof='cd ~/steamcmd/fof_main/fof'
alias ggf='cd ~/steamcmd/fof_gg/fof'
alias ggf2='cd ~/steamcmd/fof_gg2/fof'
alias foz='cd ~/steamcmd/fof_foz/fof'
alias mkf='cd ~/steamcmd/fof_mk/fof'
alias mord='cd ~/steamcmd/mordhau_main'
alias sm='cd ~/sourcemod'

# screens
alias sxs='screen -x SRCDS'
alias sfof='screen -x fof_main'
alias sggf='screen -x fof_gg'
alias sggf2='screen -x fof_2gg'
alias sfoz='screen -x fof_foz'
alias smkf='screen -x fof_mk'
alias smord='screen -x mordhau_main'
