#!/usr/bin/env sh

. ~/bin/dotfiles/python/pyenv.sh
. ~/bin/dotfiles/python/pipx.sh
. ~/bin/dotfiles/node/nvm.sh

# By default Vagrant will not access features available on the Windows system
# from within the WSL. This means the VirtualBox and Hyper-V providers will not
# be available. To enable Windows access, which will also enable the VirtualBox
# and Hyper-V providers, set the VAGRANT_WSL_ENABLE_WINDOWS_ACCESS environment
# variable:
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"

export CHROME_BIN="/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"

# directory shortcuts
export USER_DIR="/mnt/c/Users/$USER" 
alias bill='cd $USER_DIR'

export WORK_DIR="$USER_DIR/work"
alias work='cd $WORK_DIR'

export WEBAPP_DIR="$WORK_DIR/amp/webapp"
export WEBAPP_VAGRANT_DIR=$WEBAPP_DIR/vm
alias webapp='cd $WEBAPP_DIR'

export MOBILE_DIR="$WORK_DIR/volt/mobile"
alias mobile='cd $MOBILE_DIR'

# convenience functions
amp () ( 
    cd $WEBAPP_VAGRANT_DIR && vagrant "$@"
)

gli () {
    cmd.exe /C start $GITLAB_URL/$GITLAB_PROJECT/issues/$1
}
