#!/usr/bin/env sh

. ~/bin/dotfiles/python/pyenv.sh
. ~/bin/dotfiles/node/nvm.sh

# By default Vagrant will not access features available on the Windows system
# from within the WSL. This means the VirtualBox and Hyper-V providers will not
# be available. To enable Windows access, which will also enable the VirtualBox
# and Hyper-V providers, set the VAGRANT_WSL_ENABLE_WINDOWS_ACCESS environment
# variable:
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"

export CHROME_BIN="/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"

# directory shortcuts
export WIN_USER_DIR="/mnt/c/Users/$USER" 
export WIN_DOTFILES="$WIN_USER_DIR/bin/dotfiles"
export WIN_WORK_DIR="$WIN_USER_DIR/work"

export WEBAPP_DIR="$WIN_WORK_DIR/amp/webapp"
export WEBAPP_VAGRANT_DIR=$WEBAPP_DIR/vm
alias webapp='cd $WEBAPP_DIR'

export MOBILE_DIR="$WIN_WORK_DIR/volt/mobile"
alias mobile='cd $MOBILE_DIR'

export FARAD_DIR="$WORK_DIR/farad"
alias farad='cd $FARAD_DIR'

export CR_DIR="$WORK_DIR/ConditionReport"
alias cr='cd $CR_DIR'

# convenience functions
amp () ( 
    cd $WEBAPP_VAGRANT_DIR && vagrant "$@"
)

gli () {
    cmd.exe /C start $GITLAB_URL/$GITLAB_PROJECT/issues/$1
}

# enable ipython
alias ipython='python3 -m IPython'

export CURRENT_PROJECT="$WORK_DIR/farad"
