#!/usr/bin/env sh
exit 1

# execute current line in bash from vim
# :.w !bash

# symlink rc files
ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/gvimrc ~/.gvimrc

# install node for coc-nvim
curl -sL install-node.vercel.app/lts | bash

# install plugins
vim +PlugInstall +qall
