#!/usr/bin/env bash

# Symlink to this file from ~/.bashrc
# ln -s ~/bin/dotfiles/bashrc ~/.bashrc 

. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases
. ~/bin/dotfiles/bash/functions

. ~/bin/dotfiles/git/git.sh
. ~/bin/dotfiles/git/git-completion.bash
