#!/bin/sh

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto -p'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#Default command overrides
alias rm='rm -i'

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

#SRCDS
alias sxs='screen -x SRCDS'

# directory shortcuts
alias tf2='cd ~/servers/srcds/tf2/orangebox/tf/'
alias sm='cd ~/current_work/sourcemod'
alias ra='cd ~/current_work/rails_projects'

#vim startups
alias vimn='vim -c "NERDTree" '
alias gvimn='gvim -c "NERDTree" '
