#!/usr/bin/env sh

# enable color support of ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# command line prompt
GIT_PS1_SHOWDIRTYSTATE=1
PS1="\e]0;\u@\h \w\a\[\033[00;34m\]\u\[\033[00;31m\]@\[\033[00;34m\]\h \[\033[04;34m\]\w\[\033[00;32m\] \$\[\033[00;0m\]\n"
PS2="\[\033[00;32m\]> \[\033[00;0m\]"
PS3=
PS4="\[\033[00;32m\]+ \[\033[00;0m\]"
